---

- name: Installing NTP package
  apt:
    name: ntp
    state: present

- name: Copy NTP conf. template
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: Update NTP server address
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server'
    line: 'server {{ ntp_server }}'

- name: Start NTP service
  service:
    name: ntp
    state: started
