---
# tasks file for user_mgmt

- name: Create users and set passwords
  become: yes
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    with_items: "{{ users }}"
