- name: install monitoring stack
  hosts: mentoring_hosts
  become: yes
  roles:
  - prometheus
  - grafana

- name: install node-exporter
  hosts: mentoring_hosts
  become: yes
  roles:
  - node-exporter
